export const theme = {
  list: {
    nested: {
      listitem: 'list-none'
    },
    ul: 'list-disc pl-4',
    ol: 'list-decimal pl-4',
    listitem: '',
  },
  text: {
      bold: 'font-bold',
      underline: 'text-decoration-line: underline',
      italic: 'italic',
      strikethrough: 'line-through',
  },
  code: 'editorCode',
  codeHighlight: {
    atrule: 'text-purple-500',
    attr: 'text-emerald-400',
    boolean: 'text-blue-500',
    builtin: 'text-amber-500',
    cdata: 'text-gray-500',
    char: 'text-teal-400',
    class: 'text-cyan-500',
    comment: 'text-gray-400 italic',
    constant: 'text-indigo-500',
    deleted: 'text-red-500 line-through',
    doctype: 'text-gray-500',
    entity: 'text-orange-500',
    function: 'text-sky-500',
    important: 'text-rose-500',
    inserted: 'text-green-500',
    keyword: 'text-primary-500',
    namespace: 'text-purple-400',
    number: 'text-amber-400',
    operator: 'text-gray-400',
    prolog: 'text-gray-500',
    property: 'text-blue-400',
    punctuation: 'text-gray-400',
    regex: 'text-orange-400',
    selector: 'text-rose-400',
    string: 'text-emerald-500',
    symbol: 'text-yellow-500',
    tag: 'text-blue-500',
    url: 'text-blue-400 underline',
    variable: 'text-fuchsia-500',
  },
}